network:
  endpoints:
  # Sent to pi
    nano_to_pi:
      port: 5005

    elegoo_to_pi:
      port: 5006

    mac_cmd:
      port: 5007

    mac_pulse:
      port: 5008

    pi2_pulse:
      port: 5009

    vid_cmd:
      port: 5016


  # Sent from pi
    nano_to_mac:
      port: 5010

    elegoo_to_mac:
      port: 5011

    pi_to_mac_position:
      port: 5012

    pi_to_motor:
      port: 5013

    pi_to_pi2:
      port: 5014

    pi_to_mac_vid:
      port: 5015


intervals:
  # 0.1 = 100 ms = 10 Hz
  # 0.01 = 10 ms = 100 Hz
  nano_read:      0.1
  elegoo_read:    0.1
  mac_cmd_read:   0.1
  mac_pulse_read: 1000 # ms
  pi2_pulse_read: 1

  nano_send: 1
  elegoo_send: 2
  pi_position: 3
  motor_cmd: 4
  pi2_cmd: 5

  # Motor response
  f_uss_threshold: 5
  l_uss_threshold: 5
  r_uss_threshold: 5
  turning_time_threshold: 0.1

  # timeout
  mac_hb_timeout_interval:   5
  mac_cmd_timeout_interval: 10
  pi2_hb_timeout_interval:   5


